name: Installation et Publication de l’application

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation nginx
        run: |
          sudo apt update
          sudo apt install -y nginx
          sudo mkdir -p /var/www/site
          sudo chown -R www-data:www-data /var/www/site

      - name: Configuration nginx
        run: |
          sudo tee /etc/nginx/sites-available/site > /dev/null <<EOF
          server {
              listen 80;
              server_name _;
              root /var/www/site;
              index index.html;

              location / {
                  try_files \$uri \$uri/ =404;
              }
          }
          EOF

          sudo ln -sf /etc/nginx/sites-available/site /etc/nginx/sites-enabled/site
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t

          sudo cp index.html /var/www/site/index.html
          sudo chown www-data:www-data /var/www/site/index.html

      - name: Redémarrage nginx
        run: |
          sudo systemctl enable nginx
          sudo systemctl restart nginx

